// -*- C++ -*-
//
// generated by wxGlade 0.7.2 on Sun Jan 29 12:37:08 2017
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "luke_dmm_wx.h"

// begin wxGlade: ::extracode
// end wxGlade



MyFrame::MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    text_ctrl_value = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    text_ctrl_unit = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    const wxString radio_box_mode_choices[] = {
        _("Voltage"),
        _("Current"),
    };
    radio_box_mode = new wxRadioBox(this, wxID_ANY, _("Mode"), wxDefaultPosition, wxDefaultSize, 2, radio_box_mode_choices, 2, wxRA_SPECIFY_ROWS);

    set_properties();
    do_layout();
    // end wxGlade
}


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(_("Luke DMM"));
    text_ctrl_value->SetMinSize(wxSize(200, 50));
    text_ctrl_unit->SetMinSize(wxSize(75, 50));
    radio_box_mode->SetSelection(0);
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(300, 20, 0, 0, 0);
    sizer_2->Add(20, 20, 0, 0, 0);
    sizer_2->Add(text_ctrl_value, 0, 0, 0);
    sizer_2->Add(text_ctrl_unit, 0, 0, 0);
    sizer_1->Add(sizer_2, 1, 0, 0);
    sizer_1->Add(radio_box_mode, 0, wxALIGN_CENTER, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

